version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/arttrade
  db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "25022002"
      POSTGRES_DB: arttrade
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
